### PR TITLE
Revert "Feature side bar" for TSe

### PR DESCRIPTION
**Pull request by thankgodr**
Reverts thankgodr/Embedding-Images-and-Video#3 for TSE to approve

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @thankgodr @sipe-daniel , 👋 You have done a great job in this project 👏 

* [x] Fix image links which is broken in live demo
image

* [ ] [Optional] Remove that border which covers entire page
> NOTE: Don't merge the dev/feature branch to master before getting approval from TSE, If you want to host for live demo, use https://zeit.co/home or https://raw.githack.com/.
 
----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by shshamim63** [comment]
## Status :red_circle:  [!! Changes Required !!] :red_circle: 
___
Hi @thankgodr  and @sipe-daniel :wave: ,
Awesome job :clap: . Project contains readme, css folder contains css files only(Organized files). But there are some issues that are blocking me to approve this project. And I believe that you guys will cover it easily.
___
#### Please follow the instructions below to complete this project.
___
### :spades: [Mandatory Changes] :spades: 
___
1. You were asked to check HTML markup with this validator https://validator.w3.org/#validate_by_upload. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by thankgodr** [comment]
Fixed

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @thankgodr, @sipe-daniel , 👋 You have done a great job in this project 👏 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Pull request merged**
